---
_public_key: 8a928d5850e4cea4213e247aaebed698ee48f05fffd32d13e5adff262f20d40d
secrets:
  sley-weatherapp:
    all-clusters:
      mysql_root_password: "EJ[1:dLvguBFlsbrX0jeKoJHADH3FWCW8RWHQ1wQdFF8valE=:IHKE4F+P/D5j823PmklBH/Cc6X+SVLxH:GvqJWBwaA9dYVfWddPokbssa8Us7HCo8MyES9344Tc+/]"
